export const API_BASE_URL = "http://localhost:3000/api/v1";

export const COUNTRIES = [
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Ireland",
  "Portugal",
  "Austria",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Greece",
  "Turkey",
  "Russia",
  "Ukraine",
  "China",
  "Japan",
  "South Korea",
  "Singapore",
  "Malaysia",
  "Thailand",
  "Vietnam",
  "Indonesia",
  "Philippines",
  "Sri Lanka",
  "Nepal",
  "Bangladesh",
  "Pakistan",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Oman",
  "South Africa",
  "Egypt",
  "Morocco",
  "Kenya",
  "Nigeria",
  "Brazil",
  "Argentina",
  "Chile",
  "Peru",
  "Mexico",
  "Colombia",
  "New Zealand",
];

export const TRIP_CATEGORY = {
  LEISURE: "leisure",
  BUSINESS: "business",
  ADVENTURE: "adventure",
  FAMILY: "family",
  FRIENDS: "friends",
  SOLO: "solo",
  ROMANTIC: "romantic",
  ROAD_TRIP: "road trip",
  BACKPACKING: "backpacking",
  PILGRIMAGE: "pilgrimage",
  WELLNESS: "wellness",
  EDUCATIONAL: "educational",
  CULTURAL: "cultural",
  SPORTS: "sports",
  OTHER: "other",
};

export const TRIP_STATUS = {
  DRAFT: "draft",
  PLANNED: "planned",
  BOOKED: "booked",
  IN_PROGRESS: "in progress",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
  POSTPONED: "postponed",
};
